---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - sqlite3
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Get source code
  ansible.builtin.unarchive:
    src: https://github.com/Sonarr/Sonarr/releases/download/v{{ sonarr_version }}/Sonarr.main.{{ sonarr_version }}.linux-x64.tar.gz
    dest: /opt
    remote_src: true

- name: Add sonarr.service
  ansible.builtin.template:
    src: sonarr.service
    dest: /etc/systemd/system/sonarr.service
    mode: '0644'
  become: true
  notify:
    - Sonarr_reload_systemd
    - Restart_sonarr
