---

- name: Create /var/lib/sonarr folder
  ansible.builtin.file:
    path: /var/lib/sonarr
    state: directory
    mode: '0755'
    owner: '{{ sonarr_user }}'
    group: '{{ sonarr_user }}'
  become: true
